name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Get version from package.json
        id: get_version
        shell: pwsh
        run: |
          $version = node -p "require('./package.json').version"
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create .env file
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" > .env
          echo "VITE_GITHUB_PAT=${{ secrets.VITE_GITHUB_PAT }}" >> .env
          echo "VITE_GITHUB_BASE_URL=${{ secrets.VITE_GITHUB_BASE_URL }}" >> .env
          echo "VITE_GITHUB_USERNAME=${{ secrets.VITE_GITHUB_USERNAME }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_GITHUB_PAT: ${{ secrets.VITE_GITHUB_PAT }}
          VITE_GITHUB_BASE_URL: ${{ secrets.VITE_GITHUB_BASE_URL }}
          VITE_GITHUB_USERNAME: ${{ secrets.VITE_GITHUB_USERNAME }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}

      - name: Build Windows app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          files: |
            release/${{ env.VERSION }}/builder-debug.yml
            release/${{ env.VERSION }}/builder-effective-config.yaml
            release/${{ env.VERSION }}/latest.yml
            release/${{ env.VERSION }}/VyNex-Windows-*-Setup.exe
            release/${{ env.VERSION }}/VyNex-Windows-*-Setup.exe.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}